[app]
env = "dev"
log_level = "INFO"
output_dir = "data/out"

[pricing]
# Add your knobs used by plan_and_cost/task_detect here (examples):
# default_tokens_in_per_request = 1500
# default_tokens_out_per_request = 600
# storage_cost_per_gb_month = 0.12
